Project ShareIt v0.0.1
KosSpb/java-shareit pull request #1
Opened 2023-06-05 00:16 UTC by KosSpb

feat: добавить классы User, UserDto, UserController, UserService, UserStorage для работы с пользователями;
feat: добавить классы Item, ItemDto, ItemController, ItemService, ItemStorage для работы с вещами;
feat: добавить мапперы для преобразования объектов Item в ItemDto и обратно, а также User в UserDto и обратно;
feat: реализовать классы InMemoryItemStorage и InMemoryUserStorage для хранения пользователей и вещей в памяти приложения;
feat: добавить аннотацию @NullableNotBlank, совмещающую функционал аннотаций @NotNull и @NotBlank;
feat: добавить класс ErrorHandler для обработки исключений, а также создать исключения для частных случаев;

2023-06-05 19:18 UTC, alexache requested changes

2023-06-05 19:18 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        log.info("PaI-1. updateItem - item \"{}\" with id {} was updated.",
PoI, PaI?

2023-06-05 19:18 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +@Component
А эта аннотация как тут оказалась?

2023-06-05 19:18 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private Integer rentCounter;
Лучше придерживаться списка полей из ТЗ

2023-06-05 19:18 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Long ownerId;
Лучше бы это был полноценный объект User

2023-06-05 19:18 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private List<Long> renterIds;
А для чего эта информация?

2023-06-05 19:18 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/User.java
> +    private List<Long> items;
Это тоже выглядит немного избыточным

2023-06-05 19:18 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +        if (userDto.getEmail() == null) {
Почему бы не проверять это аннотацией?

2023-06-05 19:18 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/dao/impl/InMemoryUserStorage.java
> +            return Optional.empty();
Мне кажется, более правильно бросать исключение. Иначе не очень очевидный контракт, что на пустой опшинал именно повтор имейла. Такие контракты со временем опасны

2023-06-05 19:18 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/dao/impl/InMemoryUserStorage.java
> +        if (!users.containsKey(id)) {
Это какое-то усложнение, почему не просто Optional.ofNullable(users.get(id)) ?

2023-06-05 19:18 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/dao/impl/InMemoryUserStorage.java
> +        if (!emailsOfUsers.containsKey(user.getEmail())) {
Не очень соотноситься с тем, что метод "check"

2023-06-05 19:18 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        if (itemDto.getName() == null) {
Почему валидация не через аннотации на ДТО?

2023-06-05 19:18 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        User user = userStorage.getUserById(userId).orElseThrow(() -> {
Это немного усложнение. Проще хранить маппинг владельцев на вещи в сторадже вещей, тогда такой запрос получения вещей владельца будет очень простым

2023-06-05 19:18 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/dao/impl/InMemoryItemStorage.java
> +        if (item.getIsAvailable() != null && item.getName() == null && item.getDescription() == null) {
Какая-та очень сложная логика с очень запутанными условиями и большим количеством запросов к стораджу

2023-06-05 19:18 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/dao/impl/InMemoryItemStorage.java
> +                .filter((Item item) -> item.getName().toLowerCase().contains(text.toLowerCase())
text.toLowerCase лучше сделать единожды

2023-06-06 15:38 UTC, KosSpb commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        log.info("PaI-1. updateItem - item \"{}\" with id {} was updated.",
Да, знаю что выглядит немного странно. Когда групповой проект делали, то другой ревьюер поделился своей рабочей практикой, и сказал: "Алгоритмы в рабочих проектах имеют название/номер, чаще и то и то, например у меня на работе дают названия на подобии TS-1 TS-2 TS-3 в документации соответственно есть эти же номера, а далее в коде в логах мы пишем "TS-1 создание того того" и если у кого-то есть вопрос по реализации он идет в документацию и ищет по номеру алгоритма". Но видимо я как-то неправильно понял принцип. Уберу тогда это.

2023-06-06 16:02 UTC, KosSpb commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +@Component
Убрал.

2023-06-06 16:59 UTC, KosSpb commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private Integer rentCounter;
Исправил. Немного смутило предложение из текста ТЗ: "Например, вы можете не захотеть показывать пользователям владельца вещи (поле owner), а вместо этого возвращать только информацию о том, сколько раз вещь была в аренде". Решил что это в следующих ТЗ нужно будет реализовывать, вот и добавил сразу.

2023-06-06 17:04 UTC, KosSpb commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Long ownerId;
Исправил.

2023-06-06 17:07 UTC, KosSpb commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private List<Long> renterIds;
Убрал. А создавал всё по той же причине, которую описал чуть выше, для "возвращать только информацию о том, сколько раз вещь была в аренде".

2023-06-06 17:09 UTC, KosSpb commented on src/main/java/ru/practicum/shareit/user/User.java
> +    private List<Long> items;
Удалил.

2023-06-06 21:32 UTC, KosSpb commented on src/main/java/ru/practicum/shareit/user/dao/impl/InMemoryUserStorage.java
> +            return Optional.empty();
Исправил.

2023-06-06 21:42 UTC, KosSpb commented on src/main/java/ru/practicum/shareit/user/dao/impl/InMemoryUserStorage.java
> +        if (!users.containsKey(id)) {
Исправил.

2023-06-06 22:05 UTC, KosSpb commented on src/main/java/ru/practicum/shareit/user/dao/impl/InMemoryUserStorage.java
> +        if (!emailsOfUsers.containsKey(user.getEmail())) {
Переименовал.

2023-06-06 23:29 UTC, KosSpb commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        User user = userStorage.getUserById(userId).orElseThrow(() -> {
Я исправил получение вещей владельца, но если честно, то не совсем понял к какому именно месту этого метода вопрос. User мне нужен для поиска вещей в сторадже вещей, соответственно придётся в любом случае обращаться к стораджу юзеров. А как нам говорили, обращаться из одного стораджа в другой это плохая практика, и лучше это делать на уровне сервисов. Поэтому надеюсь я всё же верно внёс коррективы.

2023-06-06 23:52 UTC, KosSpb commented on src/main/java/ru/practicum/shareit/item/dao/impl/InMemoryItemStorage.java
> +        if (item.getIsAvailable() != null && item.getName() == null && item.getDescription() == null) {
Постарался упростить.

2023-06-07 14:32 UTC, KosSpb commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +        if (userDto.getEmail() == null) {
Переделал на проверку через аннотации.

2023-06-07 14:36 UTC, KosSpb commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        if (itemDto.getName() == null) {
Нужна была валидация только во время создания вещи, поэтому реализовал именно так. Сейчас почитал про валидацию по группам и переделал это на аннотации.

2023-06-07 14:41 UTC, KosSpb commented on src/main/java/ru/practicum/shareit/item/dao/impl/InMemoryItemStorage.java
> +                .filter((Item item) -> item.getName().toLowerCase().contains(text.toLowerCase())
Исправил.

2023-06-08 06:46 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        log.info("PaI-1. updateItem - item \"{}\" with id {} was updated.",
Видимо не хватает "документации" :) Я с такой практикой не сталкивался, особенно в логах. В коммит сообщениях - да, ссылки на тикеты, тогда можно отслеживать цепочку откуда и почему это было сделано

2023-06-08 16:25 UTC, alexache approved these changes

2023-06-08 19:46 UTC, merged