Project ShareIt v0.2.0
KosSpb/java-shareit pull request #2
Opened 2023-06-28 14:39 UTC by KosSpb

feat: добавить AlreadyDoneException, NotAvailableException и обработку для них в классе ErrorHandler;
refactor: обозначить интерфейсы UserStorage и ItemStorage, классы InMemoryUserStorage и InMemoryItemStorage аннотацией @Deprecated, как утратившие актуальность;
feat: реализовать подключение к базе данных через application.properties и хранение данных в ней с помощью интерфейсов UserRepository, ItemRepository, BookingRepository, CommentRepository;
refactor: изменить работу сервисных классов UserService и ItemService с учётом появления возможности хранить данные в базе данных, и под использование Spring Data JPA;
feat: добавить модели данных Booking и Comment;
feat: реализовать функции бронирования вещей при помощи классов BookingController, BookingService, BookingStatus, BookingState;
feat: добавить возможность просматривать даты бронирования при просмотре вещей;
feat: реализовать функцию оставления отзывов после бронирования вещи в классах ItemController, ItemService;
refactor: добавить в классы моделей данных аннотации для работы со Spring Data JPA;
refactor: переименовать DTO модель данных ItemDto в ItemRequestDto;
feat: добавить дополнительные DTO модели данных BookingForItemDto, BookingResponseDto, BookingRequestDto, CommentDto, ItemForBookingDto, ItemResponseDto, UserForBookingDto;
feat: добавить интерфейс-проекцию BookingShort;
feat: добавить маппер-классы BookingMapper, CommentMapper;
feat: создать интерфейсы FirstOrder и SecondOrder для обозначения порядка валидации через аннотации;

2023-06-29 19:25 UTC, alexache requested changes

2023-06-29 19:25 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +@Data
@Data включает в себя @EqualsAndHashcode, которую нельзя использовать на JPA моделях из-за некорректной работы

2023-06-29 19:25 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        if (item.getOwner().equals(user)) {
достаточно сверки их айди, а не полного соответствия

2023-06-29 19:25 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/dao/BookingRepository.java
> +    @Query("select b from Booking b " +
Через имя метода можно писать запросы и по джоин таблицам

2023-06-29 19:25 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +                    itemResponseDto.setComments(commentRepository.findByItem(item).stream()
запросы к базе в цикле под запретом

2023-06-29 19:25 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +                    addLastAndNextBookingToItemDto(item, itemResponseDto);
Здесь запрос к базе внутри цикла

2023-06-29 19:25 UTC, alexache commented on src/main/resources/application.properties
> +spring.config.activate.on-profile=ci,test,default
Нет, неправильно использовать H2 по дефолту

2023-06-29 21:31 UTC, KosSpb commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +@Data
Переопределил без аннотации.

2023-06-29 21:43 UTC, KosSpb commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        if (item.getOwner().equals(user)) {
Исправлено.

2023-06-29 22:11 UTC, KosSpb commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +                    itemResponseDto.setComments(commentRepository.findByItem(item).stream()
Исправлено.

2023-07-01 18:20 UTC, KosSpb commented on src/main/java/ru/practicum/shareit/booking/dao/BookingRepository.java
> +    @Query("select b from Booking b " +
Исправлено.

2023-07-01 18:21 UTC, KosSpb commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +                    addLastAndNextBookingToItemDto(item, itemResponseDto);
Надеюсь что исправлено.

2023-07-01 18:40 UTC, KosSpb commented on src/main/resources/application.properties
> +spring.config.activate.on-profile=ci,test,default
Убрал.

2023-07-02 09:17 UTC, alexache approved these changes

2023-07-02 09:17 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    public boolean equals(Object o) {
Если копнуть в тему equals/hashcode для JPA моделей, то можно увидеть рекомендацию использовать только id в этих методах, а не другие поля

2023-07-02 21:54 UTC, merged

2023-07-04 10:52 UTC, KosSpb commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    public boolean equals(Object o) {
Исправлено.