Add item requests
KosSpb/java-shareit pull request #3
Opened 2023-07-24 01:09 UTC by KosSpb

2023-07-24 20:11 UTC, alexache requested changes

2023-07-24 20:11 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/dao/ItemRepository.java
>      List<Item> findByOwner(User user);
А этот метод еще используется?

2023-07-24 20:11 UTC, alexache commented on src/main/java/ru/practicum/shareit/request/ItemRequestService.java
> +                    List<ItemResponseDto> items = requestedItems.stream()
Тут получается проход по списку с поиском элемента по айди запроса внутри цикла, что не самый оптимальный способ. Будет лучше и эффективнее, если заранее переделать список requestedItems в мапу с помощью коллектора и groupingBy

2023-07-24 20:11 UTC, alexache commented on src/main/java/ru/practicum/shareit/request/ItemRequestService.java
> +    public Collection<ItemRequestDtoOfResponse> getAllItemRequests(int from, int size, Long userId) {
Метод подозрительно похож на соседний с одним небольшим отличием

2023-07-24 20:11 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTest.java
> +        inOrder.verify(userRepository).findById(userId);
Не уверен, что порядок настолько важен

2023-07-24 20:11 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/dao/BookingRepositoryTest.java
> +class BookingRepositoryTest {
Тесты для репозиториев требовались только для методов с кастомными запросами (@Query вместо Derived). так что у тебя вышло больше чем требовалось (не то чтобы это слишком плохо)

2023-07-25 15:14 UTC, KosSpb commented on src/main/java/ru/practicum/shareit/item/dao/ItemRepository.java
>      List<Item> findByOwner(User user);
Да, в методе getAllBookingsForItemsOfOwner() класса BookingService. Для получения всех Item, которые есть у пользователя. В дальнейшем на основе полученного списка происходит поиск в BookingRepository.

2023-07-25 21:19 UTC, KosSpb commented on src/main/java/ru/practicum/shareit/request/ItemRequestService.java
> +                    List<ItemResponseDto> items = requestedItems.stream()
Спасибо за полезный совет. Надеюсь правильно реализовал.

2023-07-25 21:51 UTC, KosSpb commented on src/main/java/ru/practicum/shareit/request/ItemRequestService.java
> +    public Collection<ItemRequestDtoOfResponse> getAllItemRequests(int from, int size, Long userId) {
Соединил их.

2023-07-25 22:22 UTC, KosSpb commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTest.java
> +        inOrder.verify(userRepository).findById(userId);
Тут просто проверяю, что вызов сохранения в бд происходит после проверок на null. Но раз это не так важно, то удаляю.

2023-07-25 22:41 UTC, KosSpb commented on src/test/java/ru/practicum/shareit/booking/dao/BookingRepositoryTest.java
> +class BookingRepositoryTest {
Начинаю догадываться почему требовалось только для методов с кастомными запросами. Наверное в остальных методах я просто тестировал hibernate.

2023-07-27 17:34 UTC, alexache approved these changes

2023-07-31 21:13 UTC, merged