Add docker
KosSpb/java-shareit pull request #4
Opened 2023-08-04 10:36 UTC by KosSpb

2023-08-05 10:12 UTC, alexache requested changes

2023-08-05 10:12 UTC, alexache commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +        Map<String, Object> parameters = Map.of(
Можно обойтись без мапы, раз всего один элемент

2023-08-05 10:12 UTC, alexache commented on server/pom.xml
> +			<artifactId>spring-boot-starter-validation</artifactId>
В модуле сервера не должно оставаться зависимостей от валидаций

2023-08-05 10:12 UTC, alexache commented on server/src/main/java/ru/practicum/shareit/booking/BookingController.java
>              @RequestParam(value = "from", defaultValue = "0") @Min(0) int from,
Нужно избавиться от всех валидаций

2023-08-07 20:19 UTC, KosSpb commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +        Map<String, Object> parameters = Map.of(
Исправил.

2023-08-07 20:27 UTC, KosSpb commented on server/pom.xml
> +			<artifactId>spring-boot-starter-validation</artifactId>
Убрал.

2023-08-07 22:05 UTC, KosSpb commented on server/src/main/java/ru/practicum/shareit/booking/BookingController.java
>              @RequestParam(value = "from", defaultValue = "0") @Min(0) int from,
Исправил.

2023-08-08 21:14 UTC, alexache approved these changes

2023-08-08 21:33 UTC, merged